config/routes.rb
SecondApp2::Application.routes.draw do
  resources :miniposts

  resources :users

end

app/models/minipost.rb
class Minipost < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates :content, :length => { :maximum => 140 } 
   belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
has_many :miniposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/miniposts_controller.rb
class MinipostsController < ApplicationController
  # GET /miniposts
  # GET /miniposts.json
  def index
    @miniposts = Minipost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @miniposts }
    end
  end

  # GET /miniposts/1
  # GET /miniposts/1.json
  def show
    @minipost = Minipost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @minipost }
    end
  end

  # GET /miniposts/new
  # GET /miniposts/new.json
  def new
    @minipost = Minipost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @minipost }
    end
  end

  # GET /miniposts/1/edit
  def edit
    @minipost = Minipost.find(params[:id])
  end

  # POST /miniposts
  # POST /miniposts.json
  def create
    @minipost = Minipost.new(params[:minipost])

    respond_to do |format|
      if @minipost.save
        format.html { redirect_to @minipost, notice: 'Minipost was successfully created.' }
        format.json { render json: @minipost, status: :created, location: @minipost }
      else
        format.html { render action: "new" }
        format.json { render json: @minipost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /miniposts/1
  # PUT /miniposts/1.json
  def update
    @minipost = Minipost.find(params[:id])

    respond_to do |format|
      if @minipost.update_attributes(params[:minipost])
        format.html { redirect_to @minipost, notice: 'Minipost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @minipost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miniposts/1
  # DELETE /miniposts/1.json
  def destroy
    @minipost = Minipost.find(params[:id])
    @minipost.destroy

    respond_to do |format|
      format.html { redirect_to miniposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miniposts_helper.rb
module MinipostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecondApp2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/miniposts/_form.html.erb
<%= form_for(@minipost) do |f| %>
  <% if @minipost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@minipost.errors.count, "error") %> prohibited this minipost from being saved:</h2>

      <ul>
      <% @minipost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/miniposts/edit.html.erb
<h1>Editing minipost</h1>

<%= render 'form' %>

<%= link_to 'Show', @minipost %> |
<%= link_to 'Back', miniposts_path %>

app/views/miniposts/index.html.erb
<h1>Listing miniposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @miniposts.each do |minipost| %>
  <tr>
    <td><%= minipost.content %></td>
    <td><%= minipost.user_id %></td>
    <td><%= link_to 'Show', minipost %></td>
    <td><%= link_to 'Edit', edit_minipost_path(minipost) %></td>
    <td><%= link_to 'Destroy', minipost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Minipost', new_minipost_path %>

app/views/miniposts/new.html.erb
<h1>New minipost</h1>

<%= render 'form' %>

<%= link_to 'Back', miniposts_path %>

app/views/miniposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @minipost.content %>
</p>

<p>
  <b>User:</b>
  <%= @minipost.user_id %>
</p>


<%= link_to 'Edit', edit_minipost_path(@minipost) %> |
<%= link_to 'Back', miniposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>